name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup for Ember tests
      uses: mydea/actions-ember-testing@v2.0.0
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
